name: CI For BackEnd

on:
  push:
    branches: [ "BackEnd" ]
  pull_request:
    branches: [ "BackEnd" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      working-directory: 2024spring_42class_team12/FixSkkuBack

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: application.yml 생성
        run: |
          cd src/main/resources 
          echo "${{ secrets.APPLICATION }}" > ./application.yml

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash
