name: CI For BackEnd

on:
  pull_request:
    branches: [ "BackEnd" ]

jobs:
  build:
    runs-on: ubuntu-22.04 
    env:
      working-directory: 2024spring_42class_team12/FixSkkuBack

    steps: 
    - name: 체크아웃
      uses: actions/checkout

    - name: Set up JDK 17
      uses: actions/setup-java
	    with:
        distribution: 'corretto'
        java-version: '17'

    - name: application.yml 생성
      run: | 
          cd src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./application.yml
      working-directory: ${{ env.working-directory }}

    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      working-directory: ${{ env.working-directory }}
      shell: bash
